name: Issue Label
on:
  issues:
    types:
      - opened

permissions:
  issues: write # Required to add labels

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Add "question" label to new issue
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: question
