name: Release Workflow

on:
  push:
    tags:
      - 'v*'  # Trigger only for tags, adjust the pattern as needed

permissions:
  contents: write
  id-token: read  # Required for releases, if using GitHub token

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3  # Consider using v3 (stable) instead of v5

      - name: Test
        run: cat Release.txt

      - name: Build
        run: echo ${{ github.sha }} > Release.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            New release based on tag ${{ github.ref_name }}
          files: Release.txt
