name: Release Notes

on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    steps:
      - name: Checkout
        uses: actions/Checkout@v5

      - name: Test
        run: cat Release.txt

      - name: Build
        run: echo ${{ github.sha }} > Release.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            New release based on tag ${{ github.ref_name }}
          files: Release.txt
