name: Release Notes

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: cat Release.txt

      - name: Build
        run: echo ${{ github.sha }} > Release.txt

      - name: Release
        uses: softprops/action-gh-release@v2
