name: Update Major Version Tag

on:
  push:
    branches:
      - main

jobs:
  update-tag:
    if: github.event.head_commit.message != ''
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Get latest tag
        id: get-tag
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest tag: $latest_tag"
          echo "tag_name=${latest_tag}" >> $GITHUB_OUTPUT

          - name: Create GitHub Release
            uses: softprops/action-gh-release@v2
            with:
            tag_name: v1
            generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Move Major Version Tag (v1)
        run: |
          git tag -f v1
          git push origin v1 --force
          
